# mcp 4 youtube
# Source: https://github.com/ZubeidHendricks/youtube-mcp-server
# Toolathlon Version: https://github.com/lockon-n/youtube-mcp-server
type: stdio
name: youtube
params:
  command: node
  args:
    - "${local_servers_paths}/youtube-mcp-server/environment/dist/index.js"
  env:
    YOUTUBE_API_KEY: "${token.google_cloud_console_api_key}"
    PG_HOST: "${config.pg_host}"
    PG_PORT: "5434"
    PG_DATABASE: "${config.pg_database}"
    PG_USER: "eigent"
    PG_PASSWORD: "camel"
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 60
cache_tools_list: true